[package]
name = "sarosa-net"
version = "0.1.0"
authors = ["Vaelden <maugan.villatel@gmail.com>"]
build = "build.rs"

[build-dependencies]
capnpc = "*"

[dependencies]
capnp = "*"
byteorder = "*"
log = "*"
